opt_in_rules:
- attributes
- implicitly_unwrapped_optional
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- overridden_super_call
- strict_fileprivate
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call

excluded:
- Pods

file_length:
    warning: 500
    error: 1200

line_length: 175

disabled_rules:
- trailing_whitespace
- operator_usage_whitespace
- sorted_imports
- vertical_whitespace
- conditional_returns_on_newline
- redundant_string_enum_value
- cyclomatic_complexity
- function_body_length
- type_body_length
